# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Navicat.NavicatMongoDB
PackageVersion: 18.0.3
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Navicat 18 for MongoDB_is1
AppsAndFeaturesEntries:
- ProductCode: Navicat 18 for MongoDB_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Navicat\Navicat 18 for MongoDB'
Installers:
- InstallerLocale: es-ES
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_es_x64.exe
  InstallerSha256: 4dface1a6428ad08847e6f149eff20289f842163d99290515e2335645bdf8f3c
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: es-ES
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_es_x64.exe
  InstallerSha256: 4dface1a6428ad08847e6f149eff20289f842163d99290515e2335645bdf8f3c
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: en-US
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_en_x64.exe
  InstallerSha256: fcacf9c2d0fd8fce022b94656e48036d6c7233fcebcb1c44688fc2f6257b45b2
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: en-US
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_en_x64.exe
  InstallerSha256: fcacf9c2d0fd8fce022b94656e48036d6c7233fcebcb1c44688fc2f6257b45b2
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_cs_x64.exe
  InstallerSha256: 8d4d0c248faec2c8cbb0d02a0f91b51610cb9a7f53795b0fa1cc5002a7daee29
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_cs_x64.exe
  InstallerSha256: 8d4d0c248faec2c8cbb0d02a0f91b51610cb9a7f53795b0fa1cc5002a7daee29
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_ct_x64.exe
  InstallerSha256: d4223f92cd5999a666c4cbea24a2d6dad4b069aa45ccf9c30a951459ecbf1fbe
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_ct_x64.exe
  InstallerSha256: d4223f92cd5999a666c4cbea24a2d6dad4b069aa45ccf9c30a951459ecbf1fbe
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: id-ID
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_id_x64.exe
  InstallerSha256: e05d90b8a8b109738abd70b4917d9934541b39f64869e6bff0d8305a30da7ae4
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: id-ID
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_id_x64.exe
  InstallerSha256: e05d90b8a8b109738abd70b4917d9934541b39f64869e6bff0d8305a30da7ae4
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_jp_x64.exe
  InstallerSha256: 2c40a5b504ac0e35d03c1cdbe3f91f36fef5fe9af4c8884472382c9b8f09ee0a
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_jp_x64.exe
  InstallerSha256: 2c40a5b504ac0e35d03c1cdbe3f91f36fef5fe9af4c8884472382c9b8f09ee0a
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: de-DE
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_de_x64.exe
  InstallerSha256: 963f88f2c5ac209e0535686c4e999c690d07bb5270aa6ad5889c8e834d9352b9
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: de-DE
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_de_x64.exe
  InstallerSha256: 963f88f2c5ac209e0535686c4e999c690d07bb5270aa6ad5889c8e834d9352b9
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_ru_x64.exe
  InstallerSha256: 24bae80948a2f15efab27c620a89226e149142fbce8781201690ec6078d0e1ca
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_ru_x64.exe
  InstallerSha256: 24bae80948a2f15efab27c620a89226e149142fbce8781201690ec6078d0e1ca
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_pl_x64.exe
  InstallerSha256: ee1305e7f09d0d4c2072320677aabf091869fcffde3bc7e303ac80dd58f50165
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_pl_x64.exe
  InstallerSha256: ee1305e7f09d0d4c2072320677aabf091869fcffde3bc7e303ac80dd58f50165
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_fr_x64.exe
  InstallerSha256: b0553e5b9905c8117630e9d14bd6526106e5534270e5b10cd52e9b4d9b9a5b12
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_fr_x64.exe
  InstallerSha256: b0553e5b9905c8117630e9d14bd6526106e5534270e5b10cd52e9b4d9b9a5b12
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_kr_x64.exe
  InstallerSha256: c36ad972f2bb01d0550c159a1130ab98a7ab6e25aa9e79d2c98be890d330bc2d
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_kr_x64.exe
  InstallerSha256: c36ad972f2bb01d0550c159a1130ab98a7ab6e25aa9e79d2c98be890d330bc2d
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: th-TH
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_th_x64.exe
  InstallerSha256: 60862bcd568b73c8c45b6f51da70a0e82e64abbbfdfe7865a87a8a7079bfcd83
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: th-TH
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mongodb_th_x64.exe
  InstallerSha256: 60862bcd568b73c8c45b6f51da70a0e82e64abbbfdfe7865a87a8a7079bfcd83
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
