# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Navicat.NavicatMariaDB
PackageVersion: 18.0.3
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Navicat 18 for MariaDB_is1
AppsAndFeaturesEntries:
- ProductCode: Navicat 18 for MariaDB_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Navicat\Navicat 18 for MariaDB'
Installers:
- InstallerLocale: es-ES
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_es_x64.exe
  InstallerSha256: 4db3370de3e9915a6308a04d386e35bb65203f1513978c4d5d782233d4293207
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: es-ES
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_es_x64.exe
  InstallerSha256: 4db3370de3e9915a6308a04d386e35bb65203f1513978c4d5d782233d4293207
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: en-US
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_en_x64.exe
  InstallerSha256: 0d51ec2e5d3a727010ea228d0e29e4ede08a5f8b5820b7073c6ee402f74a5ea1
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: en-US
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_en_x64.exe
  InstallerSha256: 0d51ec2e5d3a727010ea228d0e29e4ede08a5f8b5820b7073c6ee402f74a5ea1
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_cs_x64.exe
  InstallerSha256: c1ee1c0337423fcc9d42a0748361fcaecfd8317163529e35e4eb6d57c9d0e410
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_cs_x64.exe
  InstallerSha256: c1ee1c0337423fcc9d42a0748361fcaecfd8317163529e35e4eb6d57c9d0e410
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_ct_x64.exe
  InstallerSha256: 3a8583c051ead7729949fc85f16ec6ef24761b258c4337917bddecdae2cd0b7c
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_ct_x64.exe
  InstallerSha256: 3a8583c051ead7729949fc85f16ec6ef24761b258c4337917bddecdae2cd0b7c
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: id-ID
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_id_x64.exe
  InstallerSha256: 738a6646a4c81af92d6f30da43f8b3dd88861eb54beb2c1b0c1da7feecf0bb22
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: id-ID
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_id_x64.exe
  InstallerSha256: 738a6646a4c81af92d6f30da43f8b3dd88861eb54beb2c1b0c1da7feecf0bb22
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_jp_x64.exe
  InstallerSha256: c5c377badf3c80cdb3a9d52c6aa071b54fade46feaebad536d1b8833d13611d8
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_jp_x64.exe
  InstallerSha256: c5c377badf3c80cdb3a9d52c6aa071b54fade46feaebad536d1b8833d13611d8
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: de-DE
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_de_x64.exe
  InstallerSha256: 46e02e890f8dbd0d2fd1c7cc723a81e22f526058c9459f4e8e348212d9db9b22
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: de-DE
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_de_x64.exe
  InstallerSha256: 46e02e890f8dbd0d2fd1c7cc723a81e22f526058c9459f4e8e348212d9db9b22
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_ru_x64.exe
  InstallerSha256: b099e7f6ed2a7e47f28e839699daa595a0f839224c0f9d642edd50c0ff7974d0
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_ru_x64.exe
  InstallerSha256: b099e7f6ed2a7e47f28e839699daa595a0f839224c0f9d642edd50c0ff7974d0
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_pl_x64.exe
  InstallerSha256: 1571b7d052c3894128bcc11b7c74da95808cd8eb8540f2fa75b74129d95553eb
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_pl_x64.exe
  InstallerSha256: 1571b7d052c3894128bcc11b7c74da95808cd8eb8540f2fa75b74129d95553eb
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_fr_x64.exe
  InstallerSha256: a62ba0be20c91548eceea5db15f1694b522ae71c443162b3d45c63b9e54cd851
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_fr_x64.exe
  InstallerSha256: a62ba0be20c91548eceea5db15f1694b522ae71c443162b3d45c63b9e54cd851
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_kr_x64.exe
  InstallerSha256: 137e66e2ec9c33e7b50fcba49c07d78d7379673d6699c6ddbbe37bc48152c6d1
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_kr_x64.exe
  InstallerSha256: 137e66e2ec9c33e7b50fcba49c07d78d7379673d6699c6ddbbe37bc48152c6d1
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: th-TH
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_th_x64.exe
  InstallerSha256: cc57011062a622077d473d3ce91b5a2134bc5247341851d9dec1147219002d6b
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: th-TH
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_mariadb_th_x64.exe
  InstallerSha256: cc57011062a622077d473d3ce91b5a2134bc5247341851d9dec1147219002d6b
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
