# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Navicat.NavicatPostgreSQL
PackageVersion: 18.0.3
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Navicat 18 for PostgreSQL_is1
AppsAndFeaturesEntries:
- ProductCode: Navicat 18 for PostgreSQL_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Navicat\Navicat 18 for PostgreSQL'
Installers:
- InstallerLocale: es-ES
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_es_x64.exe
  InstallerSha256: bee419b6c98196b3f3da3bb901b040467b46627c4a3e11c7ce3fdb0cef74cf44
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: es-ES
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_es_x64.exe
  InstallerSha256: bee419b6c98196b3f3da3bb901b040467b46627c4a3e11c7ce3fdb0cef74cf44
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: en-US
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_en_x64.exe
  InstallerSha256: c676c94c40c6a2abfb54694eb116b223b132a94bcf149a9f9eae7f384ffa8d0b
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: en-US
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_en_x64.exe
  InstallerSha256: c676c94c40c6a2abfb54694eb116b223b132a94bcf149a9f9eae7f384ffa8d0b
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_cs_x64.exe
  InstallerSha256: 45ec986e6bc59b0e2afe7d1adeb7d21875e314d0e60a7ec497f81b5a6ae71b13
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_cs_x64.exe
  InstallerSha256: 45ec986e6bc59b0e2afe7d1adeb7d21875e314d0e60a7ec497f81b5a6ae71b13
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_ct_x64.exe
  InstallerSha256: edfb407740205208a2330936e1c1e9a01efff92f382c3ae164828e27272f673b
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_ct_x64.exe
  InstallerSha256: edfb407740205208a2330936e1c1e9a01efff92f382c3ae164828e27272f673b
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: id-ID
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_id_x64.exe
  InstallerSha256: cc6c7ba5c59652ed8e1fec4ac921964250b48244bf141611a00b6fe92fb56214
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: id-ID
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_id_x64.exe
  InstallerSha256: cc6c7ba5c59652ed8e1fec4ac921964250b48244bf141611a00b6fe92fb56214
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_jp_x64.exe
  InstallerSha256: 9e32819b9ebc0c518aa13ea84591efb9ded1d63ba43108e65e456d1015972aec
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_jp_x64.exe
  InstallerSha256: 9e32819b9ebc0c518aa13ea84591efb9ded1d63ba43108e65e456d1015972aec
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: de-DE
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_de_x64.exe
  InstallerSha256: 20d09485c6a6f3949cd539242d47f43c59b9f33aa76b40ddb7e49779b4f36024
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: de-DE
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_de_x64.exe
  InstallerSha256: 20d09485c6a6f3949cd539242d47f43c59b9f33aa76b40ddb7e49779b4f36024
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_ru_x64.exe
  InstallerSha256: 945aeac923bb72850855452aa927c4acde6dc75ef27315d66bb12b2084628eb0
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_ru_x64.exe
  InstallerSha256: 945aeac923bb72850855452aa927c4acde6dc75ef27315d66bb12b2084628eb0
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_pl_x64.exe
  InstallerSha256: 101d760d1b06c15690725420928a0da19f4e6f5592d7def57e9aae4f48c3a4d0
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_pl_x64.exe
  InstallerSha256: 101d760d1b06c15690725420928a0da19f4e6f5592d7def57e9aae4f48c3a4d0
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_fr_x64.exe
  InstallerSha256: 995a171b3e66192c2f3b46048d6eddf292fc5ccbb7688293e5824586dac745d3
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_fr_x64.exe
  InstallerSha256: 995a171b3e66192c2f3b46048d6eddf292fc5ccbb7688293e5824586dac745d3
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_kr_x64.exe
  InstallerSha256: d57925d62ca067ca65eb33147dad88098faaff63b206b66c63893c5afed3ac83
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_kr_x64.exe
  InstallerSha256: d57925d62ca067ca65eb33147dad88098faaff63b206b66c63893c5afed3ac83
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: th-TH
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_th_x64.exe
  InstallerSha256: bf888343d27a4b8eec1eb2a3505fa21e3c2f2d72218f162f0695b11c3de992e6
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: th-TH
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_pgsql_th_x64.exe
  InstallerSha256: bf888343d27a4b8eec1eb2a3505fa21e3c2f2d72218f162f0695b11c3de992e6
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
