# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Navicat.NavicatPremiumLite
PackageVersion: 18.0.3
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Navicat 18 Premium Lite_is1
AppsAndFeaturesEntries:
- ProductCode: Navicat 18 Premium Lite_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Navicat\Navicat Premium Lite 18'
Installers:
- InstallerLocale: es-ES
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_es_x64.exe
  InstallerSha256: 00124caaf484ca5695aac825ee6111509c72dcb8ee7cadf79bb273efd07219c5
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: es-ES
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_es_x64.exe
  InstallerSha256: 00124caaf484ca5695aac825ee6111509c72dcb8ee7cadf79bb273efd07219c5
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: en-US
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_en_x64.exe
  InstallerSha256: f636878606f01e83b5963c5270869d0bfa9a065a32d30383a55171401a81c1fb
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: en-US
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_en_x64.exe
  InstallerSha256: f636878606f01e83b5963c5270869d0bfa9a065a32d30383a55171401a81c1fb
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_cs_x64.exe
  InstallerSha256: 0eca7768446057139ceb868ad1cb8e2f5b572882af567117ac8b5a6776f73acb
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_cs_x64.exe
  InstallerSha256: 0eca7768446057139ceb868ad1cb8e2f5b572882af567117ac8b5a6776f73acb
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_ct_x64.exe
  InstallerSha256: 5a086706a0667753c35f16d9973da09fe4bfacceb70c1e04a54a9c6c64513bb8
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_ct_x64.exe
  InstallerSha256: 5a086706a0667753c35f16d9973da09fe4bfacceb70c1e04a54a9c6c64513bb8
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: id-ID
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_id_x64.exe
  InstallerSha256: b8e3a92c70ae7577bcea954a14739bc4d7caf991eb0186d1bb6908a4200bd3ee
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: id-ID
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_id_x64.exe
  InstallerSha256: b8e3a92c70ae7577bcea954a14739bc4d7caf991eb0186d1bb6908a4200bd3ee
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_jp_x64.exe
  InstallerSha256: 1d292676fdb582a778c096980a0b6d7de72f2cc5fc67645fcf73f6bdffeca4e5
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_jp_x64.exe
  InstallerSha256: 1d292676fdb582a778c096980a0b6d7de72f2cc5fc67645fcf73f6bdffeca4e5
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: de-DE
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_de_x64.exe
  InstallerSha256: 003964a31c843401486ce544c6aee996fd9d077036b9d13392e8bb57c5b0642f
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: de-DE
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_de_x64.exe
  InstallerSha256: 003964a31c843401486ce544c6aee996fd9d077036b9d13392e8bb57c5b0642f
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_ru_x64.exe
  InstallerSha256: 76457196522969404d81f6fce3b7567f339d7426723377e6bd84ca311d8e552f
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_ru_x64.exe
  InstallerSha256: 76457196522969404d81f6fce3b7567f339d7426723377e6bd84ca311d8e552f
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_pl_x64.exe
  InstallerSha256: f0ed9cfaf2770e5b23b76316b6297dcc20cc5ab9c53e359d9b676fe6806ddc8d
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_pl_x64.exe
  InstallerSha256: f0ed9cfaf2770e5b23b76316b6297dcc20cc5ab9c53e359d9b676fe6806ddc8d
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_fr_x64.exe
  InstallerSha256: b06bd4bdae0c98a4f504012811bca4918ec9354e62e19f9399ec14f57b497e0a
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_fr_x64.exe
  InstallerSha256: b06bd4bdae0c98a4f504012811bca4918ec9354e62e19f9399ec14f57b497e0a
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_kr_x64.exe
  InstallerSha256: c768fcb136159a962e36c733c723b018ca03caebd36af5f9909a3a970e83266a
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_kr_x64.exe
  InstallerSha256: c768fcb136159a962e36c733c723b018ca03caebd36af5f9909a3a970e83266a
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: th-TH
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_th_x64.exe
  InstallerSha256: 1a9ed4d87dfd1d527a85b70b448bfcb05e4725695538347042374077d0b5e900
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: th-TH
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_lite_th_x64.exe
  InstallerSha256: 1a9ed4d87dfd1d527a85b70b448bfcb05e4725695538347042374077d0b5e900
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
