# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Navicat.NavicatDataModeler
PackageVersion: 5.0.3
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Navicat Data Modeler 5_is1
AppsAndFeaturesEntries:
- ProductCode: Navicat Data Modeler 5_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Navicat\Navicat Data Modeler 5'
Installers:
- InstallerLocale: es-ES
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_es_x64.exe
  InstallerSha256: 96ac986ee44bf5935e9f25e6bd3aa00dd47614c1aa155593994fbee5ba120696
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: es-ES
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_es_x64.exe
  InstallerSha256: 96ac986ee44bf5935e9f25e6bd3aa00dd47614c1aa155593994fbee5ba120696
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: en-US
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_en_x64.exe
  InstallerSha256: a7ad8d0d88538c5d2b78c2a1365e91fb6208284e5fd77b58135697263d5a2cf4
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: en-US
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_en_x64.exe
  InstallerSha256: a7ad8d0d88538c5d2b78c2a1365e91fb6208284e5fd77b58135697263d5a2cf4
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_cs_x64.exe
  InstallerSha256: f0dc56575061a91423659c8bab106b9ca1347906ff26bcd391049398b465141d
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_cs_x64.exe
  InstallerSha256: f0dc56575061a91423659c8bab106b9ca1347906ff26bcd391049398b465141d
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_ct_x64.exe
  InstallerSha256: 565253b47dd8d68ffddfcc51dbf5d04dab042a9b2bd1810de6d8908da65e945f
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_ct_x64.exe
  InstallerSha256: 565253b47dd8d68ffddfcc51dbf5d04dab042a9b2bd1810de6d8908da65e945f
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: id-ID
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_id_x64.exe
  InstallerSha256: 04051418f905d0593b5b87333490e88fa92c43c8f991d84267ec4faf660090c6
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: id-ID
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_id_x64.exe
  InstallerSha256: 04051418f905d0593b5b87333490e88fa92c43c8f991d84267ec4faf660090c6
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_jp_x64.exe
  InstallerSha256: ce7c3ef8e24080e048bfbb3b42b6d947dc34617adda2a23597139b03d04a6176
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_jp_x64.exe
  InstallerSha256: ce7c3ef8e24080e048bfbb3b42b6d947dc34617adda2a23597139b03d04a6176
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: de-DE
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_de_x64.exe
  InstallerSha256: 342006f457d1fb9ae681efda65a9555288fa5e0fcab1c9f752dc3e20280b1e26
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: de-DE
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_de_x64.exe
  InstallerSha256: 342006f457d1fb9ae681efda65a9555288fa5e0fcab1c9f752dc3e20280b1e26
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_ru_x64.exe
  InstallerSha256: dde5e3c003726b2926fb4446f9975a4b20b8cf78df73d14a5345e40551d756fd
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_ru_x64.exe
  InstallerSha256: dde5e3c003726b2926fb4446f9975a4b20b8cf78df73d14a5345e40551d756fd
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_pl_x64.exe
  InstallerSha256: d10de068536cbcf33c9ff6d05b07b19cce3ec63e417499c158a999bdf9bfab4c
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_pl_x64.exe
  InstallerSha256: d10de068536cbcf33c9ff6d05b07b19cce3ec63e417499c158a999bdf9bfab4c
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_fr_x64.exe
  InstallerSha256: 55b982d9fb840cd54ee646a052227b438e6fa6ccbfb20cdb3095e7d1228eac07
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_fr_x64.exe
  InstallerSha256: 55b982d9fb840cd54ee646a052227b438e6fa6ccbfb20cdb3095e7d1228eac07
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_kr_x64.exe
  InstallerSha256: 960c9a550f3ee69fd3fe3cefdd5b483aa566825047115f16f993838bf4a7a2c7
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_kr_x64.exe
  InstallerSha256: 960c9a550f3ee69fd3fe3cefdd5b483aa566825047115f16f993838bf4a7a2c7
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: th-TH
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_th_x64.exe
  InstallerSha256: ca499e1372b93c6264bd5073093c10c7bf51362732a965153e3a53fa0583b9aa
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: th-TH
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_th_x64.exe
  InstallerSha256: ca499e1372b93c6264bd5073093c10c7bf51362732a965153e3a53fa0583b9aa
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
