# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Navicat.NavicatPremium
PackageVersion: 18.0.3
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Navicat 18 Premium_is1
AppsAndFeaturesEntries:
- ProductCode: Navicat 18 Premium_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Navicat\Navicat Premium 18'
Installers:
- InstallerLocale: es-ES
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_es_x64.exe
  InstallerSha256: 8149ecb1a972a3165d97905c9486be8d1cb5f3f05c248bb5c62d8ee4d170533c
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: es-ES
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_es_x64.exe
  InstallerSha256: 8149ecb1a972a3165d97905c9486be8d1cb5f3f05c248bb5c62d8ee4d170533c
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: en-US
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_en_x64.exe
  InstallerSha256: cea971d6c562601c34f2060c7e603161fdb4ff8dae32208ef3f34a6a68ab2799
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: en-US
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_en_x64.exe
  InstallerSha256: cea971d6c562601c34f2060c7e603161fdb4ff8dae32208ef3f34a6a68ab2799
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_cs_x64.exe
  InstallerSha256: 3e792e745c39b9d48f238d0a9039761e0e0bc1346e051c4439e940be4534cd84
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_cs_x64.exe
  InstallerSha256: 3e792e745c39b9d48f238d0a9039761e0e0bc1346e051c4439e940be4534cd84
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_ct_x64.exe
  InstallerSha256: a7800a10b85a3821896d4982281f1740a61ce6fe561bfca0604d6415acc53e19
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_ct_x64.exe
  InstallerSha256: a7800a10b85a3821896d4982281f1740a61ce6fe561bfca0604d6415acc53e19
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: id-ID
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_id_x64.exe
  InstallerSha256: 329e6d91ae1bb18b71f7f85de93c8bb59b40bf1e645caaf5e657a059ea17dacb
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: id-ID
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_id_x64.exe
  InstallerSha256: 329e6d91ae1bb18b71f7f85de93c8bb59b40bf1e645caaf5e657a059ea17dacb
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_jp_x64.exe
  InstallerSha256: 6f0534dac2ea9e4934d459baf3a868feac3128b3ff1833e6f731d429bc2490d3
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_jp_x64.exe
  InstallerSha256: 6f0534dac2ea9e4934d459baf3a868feac3128b3ff1833e6f731d429bc2490d3
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: de-DE
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_de_x64.exe
  InstallerSha256: 1b6098666b5ba785f163be23e5c4d6a4eba274d3dce64427b817de9c0cc2baff
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: de-DE
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_de_x64.exe
  InstallerSha256: 1b6098666b5ba785f163be23e5c4d6a4eba274d3dce64427b817de9c0cc2baff
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_ru_x64.exe
  InstallerSha256: ffb86e6399d95e9f0f98082538b8fae8bbad2a574b9218426cb42a879953f727
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_ru_x64.exe
  InstallerSha256: ffb86e6399d95e9f0f98082538b8fae8bbad2a574b9218426cb42a879953f727
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_pl_x64.exe
  InstallerSha256: 07dbc114acfcfdba9b9b4f48e6a4377b066ecea630c4c26a414f90a347a19303
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_pl_x64.exe
  InstallerSha256: 07dbc114acfcfdba9b9b4f48e6a4377b066ecea630c4c26a414f90a347a19303
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_fr_x64.exe
  InstallerSha256: 9167d1f564f83c671e47da87bc5f3c112463b358a83a98f5231db59f8b849be3
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_fr_x64.exe
  InstallerSha256: 9167d1f564f83c671e47da87bc5f3c112463b358a83a98f5231db59f8b849be3
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_kr_x64.exe
  InstallerSha256: 74788d9368e3b8fd8ba48c6ee2bd68b1a68b6c6dd21b6e9b7091c0c95423c90d
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_kr_x64.exe
  InstallerSha256: 74788d9368e3b8fd8ba48c6ee2bd68b1a68b6c6dd21b6e9b7091c0c95423c90d
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: th-TH
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_th_x64.exe
  InstallerSha256: 865548ef6a7e1a85a858129fcd950c7031d81afa9be45e6b2eb26eaaca320962
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: th-TH
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_premium_th_x64.exe
  InstallerSha256: 865548ef6a7e1a85a858129fcd950c7031d81afa9be45e6b2eb26eaaca320962
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
