# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Navicat.NavicatSQLite
PackageVersion: 18.0.3
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Navicat 18 for SQLite_is1
AppsAndFeaturesEntries:
- ProductCode: Navicat 18 for SQLite_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Navicat\Navicat 18 for SQLite'
Installers:
- InstallerLocale: es-ES
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_es_x64.exe
  InstallerSha256: 8fe45fbe272738d6b9288e7c7987a5b9e4cea37e0681f82a8403de96fbc4b5d3
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: es-ES
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_es_x64.exe
  InstallerSha256: 8fe45fbe272738d6b9288e7c7987a5b9e4cea37e0681f82a8403de96fbc4b5d3
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: en-US
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_en_x64.exe
  InstallerSha256: eda664fac1a8451b0182016ae701b432bcf72b7104c3fafcb11ebabe58294e4b
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: en-US
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_en_x64.exe
  InstallerSha256: eda664fac1a8451b0182016ae701b432bcf72b7104c3fafcb11ebabe58294e4b
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_cs_x64.exe
  InstallerSha256: ee6adfc433d3d5ea7876b5b030324d5d352fc1b1aeb58d795c424e9a35e58912
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_cs_x64.exe
  InstallerSha256: ee6adfc433d3d5ea7876b5b030324d5d352fc1b1aeb58d795c424e9a35e58912
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_ct_x64.exe
  InstallerSha256: 9a1faf872d09c22f83676e5b85542aaee88d64f92f8deec08d05677c6fe9e6d7
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_ct_x64.exe
  InstallerSha256: 9a1faf872d09c22f83676e5b85542aaee88d64f92f8deec08d05677c6fe9e6d7
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: id-ID
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_id_x64.exe
  InstallerSha256: 3c828950549751ff906d4d9b5f3a147859006d9b77e0b501dc321e05c747e0a8
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: id-ID
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_id_x64.exe
  InstallerSha256: 3c828950549751ff906d4d9b5f3a147859006d9b77e0b501dc321e05c747e0a8
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_jp_x64.exe
  InstallerSha256: a1358dac9e6a453adb1bb56dbcdad15eef81fd3301258f3a063590361b328f88
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_jp_x64.exe
  InstallerSha256: a1358dac9e6a453adb1bb56dbcdad15eef81fd3301258f3a063590361b328f88
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: de-DE
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_de_x64.exe
  InstallerSha256: ab2377b35d5ef0ef08c0fc53f186dfef62c32f7f4c47cb559adfd7fa5107a00c
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: de-DE
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_de_x64.exe
  InstallerSha256: ab2377b35d5ef0ef08c0fc53f186dfef62c32f7f4c47cb559adfd7fa5107a00c
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_ru_x64.exe
  InstallerSha256: 7f2abb80d4d71ff39c3b9977039ed7c58838e58f45e3e4f740637e538c0c9969
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_ru_x64.exe
  InstallerSha256: 7f2abb80d4d71ff39c3b9977039ed7c58838e58f45e3e4f740637e538c0c9969
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_pl_x64.exe
  InstallerSha256: 7965346bd0f8509896fef5d9d0658667fffc48f4491d64b015d4abbb728346bb
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_pl_x64.exe
  InstallerSha256: 7965346bd0f8509896fef5d9d0658667fffc48f4491d64b015d4abbb728346bb
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_fr_x64.exe
  InstallerSha256: ea0ca1f6ddc9c58ee26eb6d6d919e95a334649b831ddddd09a5c28bb40d10940
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_fr_x64.exe
  InstallerSha256: ea0ca1f6ddc9c58ee26eb6d6d919e95a334649b831ddddd09a5c28bb40d10940
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_kr_x64.exe
  InstallerSha256: f4d68c08f5e8828e7ad877f9c18fd1814f4daf3c54bc30a9274507780dfca1e2
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_kr_x64.exe
  InstallerSha256: f4d68c08f5e8828e7ad877f9c18fd1814f4daf3c54bc30a9274507780dfca1e2
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: th-TH
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_th_x64.exe
  InstallerSha256: 15ca8ef49c5adf4b9a64821628ed055985b01327c091ff7c2f998117a5a4e566
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: th-TH
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_sqlite_th_x64.exe
  InstallerSha256: 15ca8ef49c5adf4b9a64821628ed055985b01327c091ff7c2f998117a5a4e566
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
