# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Navicat.NavicatBI
PackageVersion: 3.0.3
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Navicat BI 3_is1
AppsAndFeaturesEntries:
- ProductCode: Navicat BI 3_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Navicat\Navicat BI 3'
Installers:
- InstallerLocale: es-ES
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_es_x64.exe
  InstallerSha256: b77be52dcd4a3230307ff53df5fc82c87be4a608b93635ace7b49e264256bc3e
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: es-ES
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_es_x64.exe
  InstallerSha256: b77be52dcd4a3230307ff53df5fc82c87be4a608b93635ace7b49e264256bc3e
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: en-US
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_en_x64.exe
  InstallerSha256: 314d17defed8d207d9cf6536afe22d22d16cf80fe5335715903a3bea093543ae
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: en-US
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_en_x64.exe
  InstallerSha256: 314d17defed8d207d9cf6536afe22d22d16cf80fe5335715903a3bea093543ae
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_cs_x64.exe
  InstallerSha256: 167aaadd4b4a9bc637a58d30e30023925ce0cb4f2abfda1f000da89616e8dd70
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_cs_x64.exe
  InstallerSha256: 167aaadd4b4a9bc637a58d30e30023925ce0cb4f2abfda1f000da89616e8dd70
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_ct_x64.exe
  InstallerSha256: 60690be7a4b3a6eb7c38046318bb92eeca7980902981959a04c43638fcc61964
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_ct_x64.exe
  InstallerSha256: 60690be7a4b3a6eb7c38046318bb92eeca7980902981959a04c43638fcc61964
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: id-ID
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_id_x64.exe
  InstallerSha256: 3910e4598113862feaef9c11d1858aba4234e4e0b053313f97dd2bd67303ce36
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: id-ID
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_id_x64.exe
  InstallerSha256: 3910e4598113862feaef9c11d1858aba4234e4e0b053313f97dd2bd67303ce36
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_jp_x64.exe
  InstallerSha256: abc95cedfaf60816e953610f320cb2489a80392df2480ad50deef8fa724915c5
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_jp_x64.exe
  InstallerSha256: abc95cedfaf60816e953610f320cb2489a80392df2480ad50deef8fa724915c5
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: de-DE
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_de_x64.exe
  InstallerSha256: aa59268eff22e6656d31e922d5612f390e6b3bc1e3f5888e4b99d03791728e53
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: de-DE
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_de_x64.exe
  InstallerSha256: aa59268eff22e6656d31e922d5612f390e6b3bc1e3f5888e4b99d03791728e53
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_ru_x64.exe
  InstallerSha256: 5d0977b5a2a461cba87002f788245f2e8c1ce6a2778755b0d91ad18d123ea3a7
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_ru_x64.exe
  InstallerSha256: 5d0977b5a2a461cba87002f788245f2e8c1ce6a2778755b0d91ad18d123ea3a7
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_pl_x64.exe
  InstallerSha256: 728e58bcc9c4bd61b21740b1b0cba06dfec868dc054998cca0cbe845426757c5
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_pl_x64.exe
  InstallerSha256: 728e58bcc9c4bd61b21740b1b0cba06dfec868dc054998cca0cbe845426757c5
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_fr_x64.exe
  InstallerSha256: 69d98814a26cf76d995a3a44f1805ec3c24aae0931b893af6bd0c535c6cafb08
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_fr_x64.exe
  InstallerSha256: 69d98814a26cf76d995a3a44f1805ec3c24aae0931b893af6bd0c535c6cafb08
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_kr_x64.exe
  InstallerSha256: 7ec96fdeacbb9ba9ef32cabe192b5bb87c779a48beeefb6aa22cb90f167a7601
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_kr_x64.exe
  InstallerSha256: 7ec96fdeacbb9ba9ef32cabe192b5bb87c779a48beeefb6aa22cb90f167a7601
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: th-TH
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_th_x64.exe
  InstallerSha256: a29060df3960067ae51cd61c320a8063d4efa31a1e3bc87290843142ae6cdfa9
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: th-TH
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatbi03_th_x64.exe
  InstallerSha256: a29060df3960067ae51cd61c320a8063d4efa31a1e3bc87290843142ae6cdfa9
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
