# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Navicat.NavicatSnowflake
PackageVersion: 18.0.3
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Navicat 18 for Snowflake_is1
AppsAndFeaturesEntries:
- ProductCode: Navicat 18 for Snowflake_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Navicat\Navicat 18 for Snowflake'
Installers:
- InstallerLocale: es-ES
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_es_x64.exe
  InstallerSha256: 61bd033c6bc277b4d5279b24fbdb5cc7e84b8b4904da7baa76477ef99848fd93
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: es-ES
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_es_x64.exe
  InstallerSha256: 61bd033c6bc277b4d5279b24fbdb5cc7e84b8b4904da7baa76477ef99848fd93
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: en-US
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_en_x64.exe
  InstallerSha256: ff2ea9da274d027bf7217bc4464a3b0015554b0f125505f5ec9276b634463532
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: en-US
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_en_x64.exe
  InstallerSha256: ff2ea9da274d027bf7217bc4464a3b0015554b0f125505f5ec9276b634463532
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_cs_x64.exe
  InstallerSha256: cacb709ee2b09af78b67e2eec9e235f1aa78a62db53457cec4b17d89b7aba998
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_cs_x64.exe
  InstallerSha256: cacb709ee2b09af78b67e2eec9e235f1aa78a62db53457cec4b17d89b7aba998
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_ct_x64.exe
  InstallerSha256: 5e4594a12c7ef4393f92fef4c477e15ab02baa7809cb0d6b3d3828d16a82551a
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_ct_x64.exe
  InstallerSha256: 5e4594a12c7ef4393f92fef4c477e15ab02baa7809cb0d6b3d3828d16a82551a
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: id-ID
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_id_x64.exe
  InstallerSha256: c3e6a53897aefeafb7dc8808dab801203839ac6fc473cb2582e6fde9ee5cb9a0
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: id-ID
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_id_x64.exe
  InstallerSha256: c3e6a53897aefeafb7dc8808dab801203839ac6fc473cb2582e6fde9ee5cb9a0
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_jp_x64.exe
  InstallerSha256: 2aa36d1f8432a2f1c399f68d9de8b453ffb70c9fcf4e40c3a39a3e8ed8419978
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_jp_x64.exe
  InstallerSha256: 2aa36d1f8432a2f1c399f68d9de8b453ffb70c9fcf4e40c3a39a3e8ed8419978
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: de-DE
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_de_x64.exe
  InstallerSha256: eef7a2fc37a35b67fcb1d1e0688770e6cc3af79f8ed6f8b2733e27ecbd7505fc
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: de-DE
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_de_x64.exe
  InstallerSha256: eef7a2fc37a35b67fcb1d1e0688770e6cc3af79f8ed6f8b2733e27ecbd7505fc
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_ru_x64.exe
  InstallerSha256: 2674104fe2d6408a03ed40df019b1ecc2c31feb660b184ae2df2da72229ece14
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_ru_x64.exe
  InstallerSha256: 2674104fe2d6408a03ed40df019b1ecc2c31feb660b184ae2df2da72229ece14
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_pl_x64.exe
  InstallerSha256: f6075dc591871c0df0ba5316f5bd7f4ae3470b5561a23e35a1c269d2c4de2cbe
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_pl_x64.exe
  InstallerSha256: f6075dc591871c0df0ba5316f5bd7f4ae3470b5561a23e35a1c269d2c4de2cbe
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_fr_x64.exe
  InstallerSha256: 01a3703ed2e8f213106029300c2bb35287a0ccbafd69d6c6af3d8cce0538ee9f
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_fr_x64.exe
  InstallerSha256: 01a3703ed2e8f213106029300c2bb35287a0ccbafd69d6c6af3d8cce0538ee9f
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_kr_x64.exe
  InstallerSha256: 44eb8e64d8f0480a3ebe44bae8876f4710767f892d2b0d7e503fbdef10fd9ebf
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_kr_x64.exe
  InstallerSha256: 44eb8e64d8f0480a3ebe44bae8876f4710767f892d2b0d7e503fbdef10fd9ebf
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: th-TH
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_th_x64.exe
  InstallerSha256: ad7b23577f88eac73904f4713c716016fcd2cc52e85ea6a49bd4d79a5bb968a5
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: th-TH
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_snowflake_th_x64.exe
  InstallerSha256: ad7b23577f88eac73904f4713c716016fcd2cc52e85ea6a49bd4d79a5bb968a5
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
