# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Navicat.NavicatDataModelerLite
PackageVersion: 5.0.3
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Navicat Data Modeler Lite 5_is1
AppsAndFeaturesEntries:
- ProductCode: Navicat Data Modeler Lite 5_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Navicat\Navicat Data Modeler Lite 5'
Installers:
- InstallerLocale: es-ES
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_es_x64.exe
  InstallerSha256: a4183c84d3c6095ebd2f774d5398ce939a9b32888e3d0412d8c85622782dbe51
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: es-ES
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_es_x64.exe
  InstallerSha256: a4183c84d3c6095ebd2f774d5398ce939a9b32888e3d0412d8c85622782dbe51
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: en-US
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_en_x64.exe
  InstallerSha256: e7e46e716ceea8808cbdf0124a1c8067fcc54a906d3f0f84ccbb03d485c79417
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: en-US
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_en_x64.exe
  InstallerSha256: e7e46e716ceea8808cbdf0124a1c8067fcc54a906d3f0f84ccbb03d485c79417
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_cs_x64.exe
  InstallerSha256: 9d7abff06f11ac4451196c8cb7f46bbeade939a015ed47d74fad5e6345863b3a
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_cs_x64.exe
  InstallerSha256: 9d7abff06f11ac4451196c8cb7f46bbeade939a015ed47d74fad5e6345863b3a
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_ct_x64.exe
  InstallerSha256: 429bd44f75b8ac0950dd91ce217447df7af2cb9b2ec686d9464e66e212d17789
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_ct_x64.exe
  InstallerSha256: 429bd44f75b8ac0950dd91ce217447df7af2cb9b2ec686d9464e66e212d17789
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: id-ID
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_id_x64.exe
  InstallerSha256: 4bcbeb6ccb20d73832b364594848504b4ca1f719c132d60a5c2025f72cc39bb9
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: id-ID
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_id_x64.exe
  InstallerSha256: 4bcbeb6ccb20d73832b364594848504b4ca1f719c132d60a5c2025f72cc39bb9
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_jp_x64.exe
  InstallerSha256: f363be5c7f314a124d828f9cc88afd9236e94a67b31bad4424a4a728d62c3ad8
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_jp_x64.exe
  InstallerSha256: f363be5c7f314a124d828f9cc88afd9236e94a67b31bad4424a4a728d62c3ad8
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: de-DE
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_de_x64.exe
  InstallerSha256: 3342178a8479d94278161406a894ae3b1bf69329293a0de7f6d3649ab785958d
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: de-DE
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_de_x64.exe
  InstallerSha256: 3342178a8479d94278161406a894ae3b1bf69329293a0de7f6d3649ab785958d
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_ru_x64.exe
  InstallerSha256: 3debd205e4e148256557181e2ffb297c6470c3a2fb4803424e45058ded56d6f4
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_ru_x64.exe
  InstallerSha256: 3debd205e4e148256557181e2ffb297c6470c3a2fb4803424e45058ded56d6f4
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_pl_x64.exe
  InstallerSha256: f9b6ffcdd4d08e7038830a291ab09b6b6d9eed606cc003f9e41a3de9a32b76f7
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_pl_x64.exe
  InstallerSha256: f9b6ffcdd4d08e7038830a291ab09b6b6d9eed606cc003f9e41a3de9a32b76f7
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_fr_x64.exe
  InstallerSha256: fb3bf3aa0958fe9c8722788ca095b55ff43c767fcfafb71671ac0c334de2d899
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_fr_x64.exe
  InstallerSha256: fb3bf3aa0958fe9c8722788ca095b55ff43c767fcfafb71671ac0c334de2d899
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_kr_x64.exe
  InstallerSha256: 8d445d997155250303b76f6bd2c07c5a2a694cc6bb454d3a193ad11b93f9bb34
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_kr_x64.exe
  InstallerSha256: 8d445d997155250303b76f6bd2c07c5a2a694cc6bb454d3a193ad11b93f9bb34
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: th-TH
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_th_x64.exe
  InstallerSha256: a8dead9f8a411f9511ea74b2fb15c5f99c23a3dd98007f0be67cc2ae5d00caf5
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: th-TH
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicatdatamodeler05_lite_th_x64.exe
  InstallerSha256: a8dead9f8a411f9511ea74b2fb15c5f99c23a3dd98007f0be67cc2ae5d00caf5
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
