# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Navicat.NavicatRedis
PackageVersion: 18.0.3
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Navicat 18 for Redis_is1
AppsAndFeaturesEntries:
- ProductCode: Navicat 18 for Redis_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Navicat\Navicat 18 for Redis'
Installers:
- InstallerLocale: es-ES
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_es_x64.exe
  InstallerSha256: 4aa2de4f8ce40a3e205ab31a13ca99d35d238346d5e679cbff5e8d0f9316d97f
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: es-ES
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_es_x64.exe
  InstallerSha256: 4aa2de4f8ce40a3e205ab31a13ca99d35d238346d5e679cbff5e8d0f9316d97f
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: en-US
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_en_x64.exe
  InstallerSha256: af617678d427754637b245e62a262610a60d6c06b1edf50d17002ac157572d52
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: en-US
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_en_x64.exe
  InstallerSha256: af617678d427754637b245e62a262610a60d6c06b1edf50d17002ac157572d52
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_cs_x64.exe
  InstallerSha256: e5701f1b07cafa7d0fbd7cecc58398bafd1e490b647dd6936a3941cc4d24b19c
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_cs_x64.exe
  InstallerSha256: e5701f1b07cafa7d0fbd7cecc58398bafd1e490b647dd6936a3941cc4d24b19c
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_ct_x64.exe
  InstallerSha256: b072f2a4d072a89809a1a5c58dbe00de301cd05344b4e4a4815c66e057e7d8f0
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: zh-Hant
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_ct_x64.exe
  InstallerSha256: b072f2a4d072a89809a1a5c58dbe00de301cd05344b4e4a4815c66e057e7d8f0
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: id-ID
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_id_x64.exe
  InstallerSha256: 44f4086ef5dac203574f103caaff501c1ca78b2445e7d62fd41619bc04bc71e4
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: id-ID
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_id_x64.exe
  InstallerSha256: 44f4086ef5dac203574f103caaff501c1ca78b2445e7d62fd41619bc04bc71e4
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_jp_x64.exe
  InstallerSha256: d3bc81aaa342edeb15bd79e4647255d42ebaace0f03b620074ac5f927cf0b5fb
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ja-JP
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_jp_x64.exe
  InstallerSha256: d3bc81aaa342edeb15bd79e4647255d42ebaace0f03b620074ac5f927cf0b5fb
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: de-DE
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_de_x64.exe
  InstallerSha256: ae476e6a784ab6912542921e7522a5155b8b53ca6d81b866d584bbe34b76abac
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: de-DE
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_de_x64.exe
  InstallerSha256: ae476e6a784ab6912542921e7522a5155b8b53ca6d81b866d584bbe34b76abac
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_ru_x64.exe
  InstallerSha256: ecf383fcb9fc1f1be64f5fe9837f49c38e7b8d0d4580f873d1458f0e797db0b5
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ru-RU
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_ru_x64.exe
  InstallerSha256: ecf383fcb9fc1f1be64f5fe9837f49c38e7b8d0d4580f873d1458f0e797db0b5
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_pl_x64.exe
  InstallerSha256: 3a33e887cb014fcf8bf254fb67e58e1f9b4d83351ddf59f1bf262f60a6e29f53
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: pl-PL
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_pl_x64.exe
  InstallerSha256: 3a33e887cb014fcf8bf254fb67e58e1f9b4d83351ddf59f1bf262f60a6e29f53
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_fr_x64.exe
  InstallerSha256: 09c4273acc199f35c42ebd578b4c2fbf474e90c5851111f960366b95c7981671
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: fr-FR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_fr_x64.exe
  InstallerSha256: 09c4273acc199f35c42ebd578b4c2fbf474e90c5851111f960366b95c7981671
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_kr_x64.exe
  InstallerSha256: 9d09df46ac9b0f7863226e0e005de18b12789fe1cbc97d24583fe1881dc7c8d6
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: ko-KR
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_kr_x64.exe
  InstallerSha256: 9d09df46ac9b0f7863226e0e005de18b12789fe1cbc97d24583fe1881dc7c8d6
  InstallerSwitches:
    Custom: /ALLUSERS
- InstallerLocale: th-TH
  Architecture: x64
  Scope: user
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_th_x64.exe
  InstallerSha256: 5b695cef956556a0997186c59b458a37c80c8bf969eda66abd06f44a66f840cb
  InstallerSwitches:
    Custom: /CURRENTUSER
- InstallerLocale: th-TH
  Architecture: x64
  Scope: machine
  InstallerUrl: https://download3.navicat.com/download/navicat18_redis_th_x64.exe
  InstallerSha256: 5b695cef956556a0997186c59b458a37c80c8bf969eda66abd06f44a66f840cb
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-29
